/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.12.1.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as counter from "../counter";
import type * as http from "../http";
import type * as lib_honoWithConvex from "../lib/honoWithConvex";
import type * as lib_withSession from "../lib/withSession";
import type * as lib_withUser from "../lib/withUser";
import type * as lib_withZod from "../lib/withZod";
import type * as presence from "../presence";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  counter: typeof counter;
  http: typeof http;
  "lib/honoWithConvex": typeof lib_honoWithConvex;
  "lib/withSession": typeof lib_withSession;
  "lib/withUser": typeof lib_withUser;
  "lib/withZod": typeof lib_withZod;
  presence: typeof presence;
}>;
