/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as crud from "../crud.js";
import type * as customFnTests from "../customFnTests.js";
import type * as customFns from "../customFns.js";
import type * as table from "../table.js";
import type * as validators from "../validators.js";
import type * as zodExample from "../zodExample.js";
import type * as zodFns from "../zodFns.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  crud: typeof crud;
  customFnTests: typeof customFnTests;
  customFns: typeof customFns;
  table: typeof table;
  validators: typeof validators;
  zodExample: typeof zodExample;
  zodFns: typeof zodFns;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
